/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:9f569236-4d8d-47a7-b8d4-dde52237c8a0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_UrNkJ38os",
    "aws_user_pools_web_client_id": "5s9e8s3cffqpma7s76s46t5b2a",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://mjgf3uafybbzvbgm56vzq37txm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "vesta21bbf0d6d3024039bd8fbf75d2c1fe4221321-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};

export default awsmobile;
