/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b0ac3ad8-86bb-4c50-b0ff-ae8c4ffe4d23",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_jM0qPxPgo",
    "aws_user_pools_web_client_id": "4fo0pkh5gmug0eaa7og98615gh",
    "oauth": {
        "domain": "vestastarter41439301-41439301-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:8080/",
        "redirectSignOut": "http://localhost:8080/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://hlygppjwgzbjjjlp56a3c4tt5a.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};
export default awsmobile;